require: rubocop-rails

AllCops:
  NewCops: disable
  Exclude:
    - "db/**/*"
    - "config/**/*"
    - "script/**/*"
    # Mainly to ignore all outdated rubocop COPS in installed gems.
    - "vendor/**/*"

Rails:
  Enabled: true

# Method definitions after `private` or `protected` isolated calls need one
# extra level of indentation.
Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Layout/EndOfLine:
  EnforcedStyle: lf
